### ISSUE TITLE
cooking.sh will create a build dir under `.`

### ISSUE THREAD

**Issue by senior7515** [hakuch/CMakeCooking#4]
Currently the expectation is to create a `$root/build` however, if you are in say 

`src/foo/bar` and call cooking via `../../../cooking.sh -r wellknown` it will create a `src/foo/bar/build` which is less than ideal :( 

we should do something like this at the top of cooking: 

instead of 

```
source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
initial_wd=$(pwd)
```

it should be 

`initial_wd=$(dirname source_dir)` 

if there is one place where opinionated things matter will be here. 

Most cmake tutorials use `$root/build`

**Comment by hakuch** [comment]
Thank you for creating the issue.

It's expected that the `build` directory is created relative to the current working directory of the shell that invokes `cooking.sh` rather than relative to the location of the `cooking.sh` file itself.

One reason for this is that a user may have many different build configurations, which all point to a single root source directory. The magic file that saves the previous invocation information (`.cooking_memory`) is also created in the current working directory rather than in the source directory itself.

Can you explain your motivation for different behavior? You should be able to choose any directory you wish via `-d`.

**Comment by senior7515** [comment]
my motivation is that usually all `build` dirs are at the `$root_of_project/build` that's the *expected* behavior of anything cmake.

**Comment by hakuch** [comment]
To achieve that with cmake-cooking, you would invoke the script inside `$root_of_project`.

As I've said, it's important to be able to support arbitrary locations for the build directory. For example, consider the way LLVM recommends building Clang: https://llvm.org/docs/CMake.html

**Comment by senior7515** [comment]
sounds good.
