### ISSUE TITLE
`SOURCE_SUBDIR` is not forwarded correctly to ingredients

### ISSUE THREAD

**Issue by senior7515** [hakuch/CMakeCooking#5]
args for SOURCE_SUBDIR is not passed correctly.

**Comment by senior7515** [comment]
args for SOURCE_SUBDIR is not passed correctly.

**Comment by hakuch** [comment]
I'll try to reproduce this bug, but off the top of my head I'm not sure why this would be happening.

**Comment by hakuch** [comment]
I was able to reproduce the issue into a failing integration test.

The way we handle `SOURCE_DIR` is a little complex, so the solution is not obvious at first glance. I'll think on it a bit.

**Comment by nacl** [comment]
I've encountered a similar problem with passing in `CMAKE_CACHE_ARGS` and `CMAKE_GENERATOR` via `EXTERNAL_PROJECT_ARGS`.

My understanding of of the root of this problem is that Cooking.cmake generates a `CONFIGURE_COMMAND` argument when the user doesn't provide one. This causes `ExternalProject_add` to ignore `SOURCE_SUBDIR` (and the `CMAKE_CACHE_ARGS`) when invoking cmake itself.

A solution to this problem that I used in a private project is to have the `_cooking_populate_ep_configure_command()` function return a `<DEFAULT>` value, which, when encountered in `_cooking_define_ep`, will result in the `CONFIGURE_COMMAND` argument not being added to `ExternalProject_add`.  The end result is the expected behavior from `SOURCE_SUBDIR` and `CMAKE_CACHE_ARGS`.

I can make a PR with the aforementioned fix (and some documentation updates) if you'd like.

**Comment by hakuch** [comment]
That would be very much appreciated, @nacl. Thanks!

**Comment by senior7515** [comment]
hey andrew! good find. i didn't really followed through the issue and just worked around it.
